spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:campus_service}
    username: ${POSTGRES_USERNAME:campus_service}
    password: ${POSTGRES_PASSWORD:change-me}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

campus:
  security:
    refresh-cookie:
      secure: ${REFRESH_COOKIE_SECURE:false}
