package com.campus.student.api;

import java.time.Instant; import java.util.*;
import com.campus.identity.domain.*; import com.campus.identity.infrastructure.security.TokenService; import com.campus.organization.application.OrganizationUnitManagementService; import com.campus.organization.domain.*;
import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.*; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.testcontainers.service.connection.ServiceConnection; import org.springframework.http.MediaType; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.test.context.ActiveProfiles; import org.springframework.test.web.servlet.MockMvc; import org.testcontainers.containers.PostgreSQLContainer; import org.testcontainers.junit.jupiter.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test") @Testcontainers class AdminStudentControllerIntegrationTest {
 @Container @ServiceConnection static PostgreSQLContainer<?> postgres=new PostgreSQLContainer<>("postgres:17.6-alpine"); @Autowired MockMvc mvc; @Autowired UserAccountRepository users; @Autowired RoleRepository roles; @Autowired PasswordEncoder passwords; @Autowired TokenService tokens; @Autowired OrganizationUnitManagementService organizations;
 @Test void restrictsAndManagesStudentRegistry() throws Exception { String user=tokens.accessToken(account("student-user@campus.example",RoleCode.USER)); mvc.perform(get("/api/v1/admin/students")).andExpect(status().isUnauthorized()); mvc.perform(get("/api/v1/admin/students").header("Authorization","Bearer "+user)).andExpect(status().isForbidden()); String admin=tokens.accessToken(account("student-admin@campus.example",RoleCode.ADMIN)); UUID unit=organizations.create("SCI","Science",OrganizationUnitType.FACULTY,OrganizationUnitStatus.ACTIVE).id(); String body=mvc.perform(post("/api/v1/admin/students").header("Authorization","Bearer "+admin).contentType(MediaType.APPLICATION_JSON).content("{\"studentNumber\":\" S001 \",\"fullName\":\" Student One \",\"email\":\"ONE@campus.example\",\"organizationUnitId\":\""+unit+"\"}" )).andExpect(status().isCreated()).andExpect(jsonPath("$.studentNumber").value("S001")).andExpect(jsonPath("$.email").value("one@campus.example")).andReturn().getResponse().getContentAsString(); String id=body.replaceFirst(".*\\\"id\\\":\\\"([^\\\"]+).*","$1"); mvc.perform(put("/api/v1/admin/students/"+id).header("Authorization","Bearer "+admin).contentType(MediaType.APPLICATION_JSON).content("{\"studentNumber\":\"S001\",\"fullName\":\"Student Updated\",\"organizationUnitId\":\""+unit+"\",\"status\":\"INACTIVE\",\"expectedVersion\":0}" )).andExpect(status().isOk()).andExpect(jsonPath("$.rowVersion").value(1)); }
 @Test void rejectsDuplicateUnavailableOrganizationAndStaleStudent() throws Exception { String admin=tokens.accessToken(account("student-errors@campus.example",RoleCode.ADMIN)); UUID active=organizations.create("ENG","Engineering",OrganizationUnitType.FACULTY,OrganizationUnitStatus.ACTIVE).id(); UUID inactive=organizations.create("ADM","Administration",OrganizationUnitType.ADMINISTRATIVE,OrganizationUnitStatus.INACTIVE).id(); String request="{\"studentNumber\":\"S002\",\"fullName\":\"Student Two\",\"organizationUnitId\":\""+active+"\"}"; String body=mvc.perform(post("/api/v1/admin/students").header("Authorization","Bearer "+admin).contentType(MediaType.APPLICATION_JSON).content(request)).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString(); mvc.perform(post("/api/v1/admin/students").header("Authorization","Bearer "+admin).contentType(MediaType.APPLICATION_JSON).content(request)).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("STUDENT_NUMBER_ALREADY_EXISTS")); mvc.perform(post("/api/v1/admin/students").header("Authorization","Bearer "+admin).contentType(MediaType.APPLICATION_JSON).content("{\"studentNumber\":\"S003\",\"fullName\":\"Student Three\",\"organizationUnitId\":\""+inactive+"\"}")).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("ORGANIZATION_UNIT_UNAVAILABLE")); String id=body.replaceFirst(".*\\\"id\\\":\\\"([^\\\"]+).*","$1"); mvc.perform(put("/api/v1/admin/students/"+id).header("Authorization","Bearer "+admin).contentType(MediaType.APPLICATION_JSON).content("{\"studentNumber\":\"S002\",\"fullName\":\"Student Two\",\"organizationUnitId\":\""+active+"\",\"status\":\"ACTIVE\",\"expectedVersion\":1}")).andExpect(status().isConflict()).andExpect(jsonPath("$.code").value("CONCURRENT_MODIFICATION")); }
 private UserAccount account(String email,RoleCode code){return users.save(UserAccount.create(UUID.randomUUID(),email,email,passwords.encode("valid-password"),AccountStatus.ACTIVE,Set.of(roles.findByCode(code).orElseThrow()),Instant.now()));}
}
